### ISSUE TITLE
Support for latest Nvidia drivers

### ISSUE THREAD

**Issue by lunasorcery** [lunasorcery/Blossom#4]
Looks like `gl_FragColor` with `#version 430` is no longer supported, since October 2021 (driver 496.13 and later).

This will inescapably affect all previously-compiled binaries, but we should at least find a workaround and implement it into the template for future releases.

**Comment by pmalin** [comment]
Hey there,

Been playing around with this. FYI, locally adding:
```
layout(location = 0) out vec4 FragColor;
```
near the top of present.frag, draw.frag and using FragColor instead of gl_FragColor ends up 2 bytes bigger in the Release build.

Making it a vec3 in present.frag saves a byte there but we're maybe just rolling the compression randomness dice at that stage.

Just writing directly to vec3 FragColor in present.frag instead of going via color ends up smaller than the original. 🤷
